src/django_prefixctl/urls.py
from django.urls import include, path

# import django_prefixctl.rest.views
from django_prefixctl import views

urlpatterns = [
    path(
        "api/",
        include(
            ("django_prefixctl.rest.urls.prefixctl", "prefixctl_api"),
            namespace="prefixctl_api",
        ),
    ),
    path("<str:org_tag>/", views.view_instance, name="prefixctl-home"),
    path("", views.org_redirect),
]

src/prefix_meta/urls.py
from django.urls import path

import prefix_meta.views as views

urlpatterns = [
    path(
        "<str:org_tag>/export/meta/prefix/location/<str:ip>/<str:masklen>",
        views.export_locations,
        name="location-export",
    )
]

src/prefixctl/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("social_django.urls", namespace="social")),
    path("", include("fullctl.django.urls")),
    path("", include("django_prefixctl.urls")),
]

handler500 = "fullctl.django.views.handle_error_500"
handler404 = "fullctl.django.views.handle_error_404"
handler403 = "fullctl.django.views.handle_error_403"
handler401 = "fullctl.django.views.handle_error_401"
handler400 = "fullctl.django.views.handle_error_400"

src/django_prefixctl/models/prefixctl.py
import secrets

import fullctl.service_bridge.pdbctl as pdbctl
import reversion
import structlog
from django.conf import settings
from django.db import models
from django.utils.translation import gettext_lazy as _
from django_grainy.decorators import grainy_model
from fullctl.django.inet.validators import validate_masklength_range
from fullctl.django.models.abstract.alert import AlertGroup as AlertGroupBase
from fullctl.django.models.abstract.alert import AlertLog as AlertLogBase
from fullctl.django.models.abstract.alert import AlertRecipient as AlertRecipientBase
from fullctl.django.models.abstract.base import HandleRefModel, SlugModel
from fullctl.django.models.concrete import Instance
from fullctl.django.models.concrete.tasks import Monitor, Task, TaskSchedule
from fullctl.django.validators import validate_alphanumeric_list
from fullctl.django.inet.validators import validate_as_set
from netfields import CidrAddressField

__all__ = (
    "ASNSet",
    "ASN",
    "PrefixSet",
    "PrefixSetIRRImporter",
    "Prefix",
    "Monitor",
    "MonitorTaskMixin",
    "ASNMonitor",
    "AlertGroup",
    "AlertTask",
    "AlertRecipient",
    "AlertLog",
    "AlertLogRecipient",
    "Instance",
    "register_prefix_monitor",
    "PREFIX_MONITOR_CLASSES",
)

PREFIX_MONITOR_CLASSES = {}

log = structlog.get_logger("django")


def register_prefix_monitor(cls):
    """
    Registers a prefix monitor class.

    Arguments:
    cls: The class to register as a prefix monitor.

    Returns:
    The class that was registered.

    Raises:
    KeyError: If a prefix monitor with the same tag is already registered.
    ValueError: If the monitor model does not inherit from HandleRefModel.
    """
    try:
        if cls.HandleRef.tag in PREFIX_MONITOR_CLASSES:
            raise KeyError(
                f"Already registered a prefix monitor with tag `{cls.HandleRef.tag}`"
            )
    except AttributeError:
        raise ValueError("Monitor model needs to be a HandleRef model")

    PREFIX_MONITOR_CLASSES[cls.HandleRef.tag] = {
        "tag": cls.HandleRef.tag,
        "cls": cls,
        "title": cls._meta.verbose_name,
    }
    return cls


def generate_secret():
    """
    Generates a URL-safe secret token.

    Returns:
    A URL-safe secret token as a string.
    """
    return f"{secrets.token_urlsafe()}"


class TaskContainer(models.Model):
    """
    A container model for tasks.
    """

    pass


@grainy_model(related="instance")
@reversion.register
class ASNSet(SlugModel):
    """
    Represents a set of Autonomous System Numbers (ASN).

    Attributes:
    instance: Foreign key to an environment instance, indicating the instance this ASN set belongs to.
    name: Name of the ASN set.
    description: Description of the ASN set, optional.
    """

    instance = models.ForeignKey(
        Instance,
        related_name="asn_set_set",
        on_delete=models.CASCADE,
        help_text=_("Environment instance id"),
    )

    name = models.CharField(max_length=255, help_text=_("name of the asn set"))
    description = models.CharField(
        max_length=255, null=True, blank=True, help_text=_("description of the asn set")
    )

    class Meta:
        db_table = "prefixctl_asnset"
        unique_together = (("instance", "name"), ("instance", "slug"))

    class HandleRef:
        tag = "asn_set"

    def __str__(self):
        return f"{self.instance}: {self.name} ({self.id})"


@grainy_model(related="asn_set")
@reversion.register
class ASN(HandleRefModel):
    """
    Represents an Autonomous System Number (ASN) within a set.

    Attributes:
    asn: The autonomous system number.
    asn_set: Foreign key to the ASNSet this ASN belongs to.
    """

    asn = models.PositiveIntegerField()
    asn_set = models.ForeignKey(
        ASNSet, related_name="asn_set", on_delete=models.CASCADE
    )

    class Meta:
        db_table = "prefixctl_asn"
        unique_together = ("asn_set", "asn")

    class HandleRef:
        tag = "asn"

    @property
    def ref(self):
        """
        Retrieves the network reference based on the ASN.

        Returns:
        The network reference object.
        """
        if not hasattr(self, "_ref"):
            self._ref = pdbctl.Network().first(asn=self.asn)
        return self._ref


@grainy_model(
    namespace="prefix",
    namespace_instance="prefix.{instance.org.permission_id}.{instance.id}",
)
@reversion.register(follow=['prefix_set'])
class PrefixSet(SlugModel):
    """
    Represents a set of IP network prefixes.

    Attributes:
    instance: Foreign key to an environment instance, indicating the instance this prefix set belongs to.
    name: Name of the prefix set.
    description: Description of the prefix set, optional.
    irr_import: Boolean indicating if automatic import of prefixes is enabled.
    irr_sources: Comma-separated sources for prefix list import.
    irr_as_set: Specifies the AS-SET for importing prefixes.
    ux_keep_list_open: UX preference, whether to keep the prefix list expanded.
    """

    instance = models.ForeignKey(
        Instance,
        related_name="prefix_set_set",
        on_delete=models.CASCADE,
        help_text=_("Environment instance id"),
    )

    name = models.CharField(max_length=255, help_text=_("name of the prefix set"))
    description = models.CharField(
        max_length=255,
        null=True,
        blank=True,
        help_text=_("description of the prefix set"),
    )

    irr_import = models.BooleanField(
        default=False, help_text=_("enable automatic import of prefixes")
    )
    irr_sources = models.CharField(
        max_length=255,
        default=None,
        blank=True,
        null=True,
        help_text=_("specify sources for prefixlist import (comma separated)"),
        validators=(validate_alphanumeric_list,),
    )
    irr_as_set = models.CharField(
        max_length=255,
        default=None,
        blank=True,
        null=True,
        help_text=_("import prefixes for AS-SET"),
        validators=(validate_as_set,),
    )

    # TODO: user centric preferences?

    ux_keep_list_open = models.BooleanField(
        default=False, help_text=_("UX Preference: Keep prefix list expanded")
    )

    class Meta:
        db_table = "prefixctl_prefix_set"
        unique_together = (("instance", "name"), ("instance", "slug"))

    class HandleRef:
        tag = "prefix_set"

    @property
    def org(self):
        """
        Retrieves the organization associated with this prefix set.

        Returns:
        The organization object.
        """
        return self.instance.org

    def __str__(self):
        return f"{self.instance}: {self.name} ({self.id})"

    @property
    def irr_import_status(self) -> str:
        """
        Will return the IRR import status as one of the following

        - pending
        - completed
        - error
        - disabled
        """

        if not self.irr_import:
            return "disabled"

        try:
            importer = self.prefix_set_irr_importer
        except PrefixSetIRRImporter.DoesNotExist:
            log.error("IRR import enabled but no importer found", prefix_set=self)
            return "error"

        try:
            importer.task_schedule
        except TaskSchedule.DoesNotExist:
            log.error("IRR import enabled but no task schedule found", prefix_set=self)
            return "error"

        recent_task = importer.task_schedule.tasks.order_by("-created").first()

        if not recent_task:
            return "pending"

        return recent_task.status

    def add_or_update_prefix(self, prefix, mask_length_range):
        """
        Add or update a prefix in this prefix set

        Arguments:
            - prefix (str): a valid ip_network prefix string
            - max_length_range(str): "exact" or "[0-9]..[0-9]"

        Returns:
            - tuple(created(bool), updated(bool))
        """

        created = False
        updated = False

        try:
            # retrieve the existing prefix
            obj = Prefix.objects.get(prefix_set=self, prefix=prefix)

            # did mask length range change?
            if obj.mask_length_range != mask_length_range:
                obj.mask_length_range = mask_length_range
                updated = True

            # is the status of the existing prefix not "ok" ?
            # set it to ok
            if obj.status != "ok":
                obj.status = "ok"
                updated = True

            # if any changes were made save the prefix
            if updated:
                obj.save()
        except Prefix.DoesNotExist:
            # prefix does not exist yet, created it
            obj = Prefix.objects.create(
                prefix_set=self,
                prefix=prefix,
                status="ok",
                mask_length_range=mask_length_range,
            )
            created = True

        return created, updated


class PrefixSetIRRImporter(Monitor):
    """
    Manages the import of IP network prefixes into a PrefixSet from IRR sources.

    Attributes:
    instance: Foreign key to an environment instance linked with this importer.
    prefix_set: OneToOne relationship to the PrefixSet being imported into.
    task_schedule: OneToOne relationship to the task schedule for this importer.
    """

    instance = models.ForeignKey(
        Instance, related_name="prefix_set_irr_importers", on_delete=models.CASCADE
    )

    prefix_set = models.OneToOneField(
        PrefixSet, related_name="prefix_set_irr_importer", on_delete=models.CASCADE
    )

    task_schedule = models.OneToOneField(
        TaskSchedule,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        help_text=_("The task schedule for the irr importer"),
    )

    class Meta:
        db_table = "prefixctl_prefix_set_irr_importer"

    class HandleRef:
        tag = "prefix_set_irr_importer"

    @property
    def schedule_interval(self):

src/django_prefixctl/models/tasks.py
import json

from fullctl.django.models import Task
from fullctl.django.tasks import register

from django_prefixctl.irr import perform_irr_import
from django_prefixctl.models.prefixctl import PrefixSet

__all__ = [
    "IRRImportTask",
]


@register
class IRRImportTask(Task):
    """
    Task for importing IP network prefixes from IRR sources into a PrefixSet.

    Attributes:
    TaskMeta: Configuration for the task, including execution limits.
    HandleRef: Reference handling for the task, including its tag.
    """

    class TaskMeta:
        limit = 1

    class HandleRef:
        tag = "task_irr_import"

    class Meta:
        proxy = True

    @property
    def generate_limit_id(self):
        """
        Generates a limit ID for the task, based on the PrefixSet ID.

        Returns:
        An identifier that limits task execution based on the PrefixSet ID.
        """
        return self.prefix_set.id

    @property
    def prefix_set(self):
        """
        Retrieves the PrefixSet associated with this task.

        Returns:
        The PrefixSet object identified by the parameter passed to the task.
        """
        return PrefixSet.objects.get(id=self.param["args"][0])

    def run(self, *args, **kwargs):
        """
        Executes the task to import IP network prefixes from IRR sources into the associated PrefixSet.

        Arguments:
        - args: Additional positional arguments (unused).
        - kwargs: Additional keyword arguments (unused).

        Returns:
        A JSON string representing the import result.
        """
        prefix_set = self.prefix_set

        as_set = prefix_set.irr_as_set
        sources = prefix_set.irr_sources
        result = perform_irr_import(self.prefix_set, as_set, sources)
        return json.dumps(result)

src/django_prefixctl/rest/views/service_bridge.py
from django.db.models import Q

from fullctl.django.rest.route.service_bridge import route
from fullctl.django.rest.views.service_bridge import (
    DataViewSet,
    HeartbeatViewSet,
    StatusViewSet,
    MethodFilter,
)

import django_prefixctl.models.prefixctl as models
from django_prefixctl.rest.serializers.service_bridge import Serializers


@route
class Status(StatusViewSet):
    checks = ("bridge_aaactl", "bridge_pdbctl")


@route
class Heartbeat(HeartbeatViewSet):
    pass


@route
class PrefixSet(DataViewSet):
    path_prefix = "/data"
    allowed_http_methods = ["GET"]
    valid_filters = [
        ("org", "instance__org__slug"),
        ("q", MethodFilter("autocomplete")),
        ("slug", "slug"),
        ("ids", "id__in")
    ]
    autocomplete = "name"
    allow_unfiltered = True

    queryset = models.PrefixSet.objects.filter(status="ok")
    serializer_class = Serializers.prefix_set

    def filter_autocomplete(self, qset, value:str):
        return models.PrefixSet.objects.filter(
            Q(name__icontains=value) | Q(slug__icontains=value)
        )

src/django_prefixctl/views.py
from django.conf import settings
from django.shortcuts import redirect, render
from fullctl.django.decorators import load_instance, require_auth

from django_prefixctl.models.prefixctl import PREFIX_MONITOR_CLASSES

# Create your views here.


def make_env(request, **kwargs):
    org = kwargs.get("org")
    r = {"env": settings.RELEASE_ENV, "version": settings.PACKAGE_VERSION}
    r.update(**kwargs)

    prefix_monitor_types = []

    for tag, mon in PREFIX_MONITOR_CLASSES.items():
        if request.perms.check(
            f"{mon['cls'].Grainy.namespace()}.{org.permission_id}", "r"
        ):
            prefix_monitor_types.append({"title": mon["title"], "tag": tag})

    r.update(PREFIX_MONITOR_CLASSES=prefix_monitor_types)
    r.update(MULTIPLE_PREFIX_MONITOR_CLASSES=(len(prefix_monitor_types) > 1))

    return r


@require_auth()
@load_instance()
def view_instance(request, instance, **kwargs):
    env = make_env(request, instance=instance, org=instance.org)
    return render(request, "theme-select.html", env)


@require_auth()
def org_redirect(request):
    return redirect(f"/{request.org.slug}/")

src/django_prefixctl/templates/prefixctl/v2/tool/asn_sets/asn-monitor-form.html
{% load static i18n %}
<form data-template="form_asn_monitor"
  data-api-base="{% url "prefixctl_api:monitor-list" org_tag=request.org.slug %}"
  data-api-method="POST"
  >
  <div data-api-submit="yes">
    <input type="hidden" name="monitor_type" value="asn_monitor" />
  </div>

  <div class="row form-check">
    <div class="col-12" data-api-submit="yes">
      <input type="checkbox" class="form-check-input" id="new_prefix_detection" name="new_prefix_detection" />
      <label for="new_prefix_detection" class="form-check-label">{% trans "New prefix detection" %}</label>
    </div>
  </div>


</form>

src/django_prefixctl/templates/prefixctl/v2/tool/asn_sets/asn-set-form.html
{% load static i18n %}
<form data-template="form_asn_set"
  data-api-base="{% url "prefixctl_api:asn_set-list" org_tag=request.org.slug %}"
  data-api-method="POST"
  >
  <div class="container-fluid">
    <div class="row mb-3">
      <div class="col-12" data-api-submit="yes">
        <label for="name" class="form-label">{% trans "Name" %}</label>
        <input type="text" class="form-control" id="name" name="name" />
      </div>
    </div>
    <div class="row mb-3">
      <div class="col-12" data-api-submit="yes">
        <label for="name" class="form-label">{% trans "Slug" %}</label>
        <input type="text" class="form-control" id="slug" name="slug" />
      </div>
    </div>
    <div class="row mb-3">
      <div class="col-12" data-api-submit="yes">
        <label for="description" class="form-label">{% trans "Description" %}</label>
        <input type="text" class="form-control" id="description" name="description" />
      </div>
    </div>
  </div>
</form>

src/django_prefixctl/templates/prefixctl/v2/tool/asn_sets/bottom-menu.html
{% load static i18n %}
<div class="section row mt-4" data-template="bottom-menu">
  <a class="secondary col-md-auto btn ms-auto d-flex" data-element="button_api_view" type="button" role="button" target="_blank">
    <div class="row align-items-center">
      <div class="col label pe-0">{% trans "API View" %}</div>
      <div class="col-auto">
        <span class="icon icon-api"></span>
      </div>
    </div>
  </a>
</div>

src/django_prefixctl/templates/prefixctl/v2/tool/asn_sets/list.html
{% load static i18n %}
<table
  class="table list-table table-borderless"
  data-api-base="{% url "prefixctl_api:asn_set-list" org_tag=request.org.slug %}"
  data-template="list">

  <tbody class="list-body">
  </tbody>

  <tbody class="templates">
    <tr data-template="row" class="firefox-border-bugfix">
      <td data-field="name" class="highlight"></td>
      <td data-field="description"></td>
      <td class="monitors"></td>
      <td data-field="controls" class="right">
          <a class="button btn" data-hover="show" data-action="add_monitor" data-btn-type="secondary">
            <span class="icon prefixctl icon-add"></span>
            <span class="label ms-1">Add Monitor</span>
          </a>
          <a class="button btn" data-hover="show" data-action="edit_asn_set">
            <span class="icon prefixctl icon-edit"></span>
          </a>
          <a
            class="button btn" data-hover="show"
            data-api-action="{id}"
            data-api-callback="remove"
            data-confirm="Remove ASN set?"
            data-api-method="DELETE"
          >
            <span class="icon prefixctl icon-delete"></span>
          </a>
          <a class="button btn" data-hover="show" data-action="list_asns">
            <span class="icon prefixctl icon-list"></span>
          </a>
          <button class="btn">
            <span class="icon icon-options"></span>
          </button>
      </td>
    </tr>
  </tbody>
</table>

<div data-template="asn_monitor_list"
  data-api-action="monitors"
  data-api-base="{% url "prefixctl_api:asn_set-detail" org_tag=request.org.slug pk=0 %}"
>
  <div class="list-body"></div>
  <div class="list-empty">
    <div class="row property">
      <div class="col field">
        {% trans "Monitor" %}: <span class="inactive">{% trans "None" %}</span>
      </div>
    </div>
  </div>

  <div class="templates">
    <div data-template="row" class="row property" style="margin-top: 0px">
      <div class="col-2 field">
        {% trans "Monitor" %}: <span class="highlight" data-field="status"></span>
      </div>
      <div class="col-3 field">
        <span>
          <span class="nowrap">
            <span class="">{% trans "New prefix detection" %}</span>:
            <span data-field="new_prefix_detection" data-toggle="checked">
            {% include "common/v2/app/checkbox.html" %}
            </span>
          </span>
        </span>
     </div>
     <div class="col field-empty right">
        <a data-action="edit_asn_monitor"><span class="icon prefixctl icon-edit"></span></a>
        <a data-api-action="delete_monitor"
          data-api-callback="remove"
          data-confirm="Remove monitor?"
          data-api-method="DELETE"><span class="icon prefixctl icon-delete"></span></a>
      </div>
    </div>
  </div>
</div>

<table>
  <tbody>
    <tr data-template="asns_list"
      data-api-base="{% url "prefixctl_api:asn_set-detail" org_tag=request.org.slug pk=0 %}"
      data-api-action="asns"
      >
      <td colspan="5" class="inner-list-container">
        <div class="grid-col-3 text-center text-uppercase">
          <div>{% trans "ASN / Network name" %}</div>
          <div>{% trans "ASN / Network name" %}</div>
          <div>{% trans "ASN / Network name" %}</div>
        </div>

        <div class="list-body grid-col-3 inner-list"></div>
        <div class="controls">
          <form
            data-api-base="{% url "prefixctl_api:asn_set-detail" org_tag=request.org.slug pk=0 %}"
            data-api-action="add_asn"
            data-api-method="POST">
              <div class="input-group justify-content-end mb-2 me-0" data-api-submit="yes">
                {% if oauth_manages_org %}
                <select name="asn" data-autocomplete-light-language="en-US" data-autocomplete-light-function="select2" id="id_asn" required data-autocomplete-light-url="/autocomplete/pdb/net">
                </select>
                {% else %}
                <input type="text" name="asn" id="id_asn" required>
                {% endif %}
                <button type="button" class="submit p-1 action">{% trans "Add" %}</button>
              </div>
          </form>
        </div>

        <div class="templates">
          <div data-template="row">
            AS<span data-field="asn"></span><span> / </span><span data-field="name" class="empty-questionmark"></span>
            <a class=""
              data-api-action="delete_asn"
              data-api-callback="remove"
              data-confirm="{% trans "Remove ASN from set?" %}"
              data-api-method="DELETE">
              <span class="icon prefixctl icon-delete "></span>
            </a>
          </div>
        </div>
      </td>
    </tr>
  </tbody>
</table>

src/django_prefixctl/templates/prefixctl/v2/tool/asn_sets/main.html
{% load static i18n %}
<div class="tool" data-component="asn_sets" data-grainy-remove="asn_set.{{ request.org.permission_id }}">

  {% include "common/v2/tool_base.html" %}

  <div class="templates">

    {% include "prefixctl/v2/tool/asn_sets/menu.html" %}
    {% include "prefixctl/v2/tool/asn_sets/list.html" %}
    {% include "prefixctl/v2/tool/asn_sets/asn-set-form.html" %}
    {% include "prefixctl/v2/tool/asn_sets/asn-monitor-form.html" %}
    {% include "prefixctl/v2/tool/asn_sets/bottom-menu.html" %}
    {% include "common/v2/app/delete_selected.html" %}

  </div>
</div>

src/django_prefixctl/templates/prefixctl/v2/tool/asn_sets/menu.html
{% load static i18n %}
<div class="section row mb-5" data-template="menu">
  <div class="col">
    <span class="heading">{% trans "ASN Sets" %}</span>
  </div>
  <button type="button" class="primary col-md-auto btn ms-auto d-flex" data-element="button_add_asn_set">
    <div class="row align-items-center">
      <div class="col label pe-0">
        {% trans "Add ASN Set" %}
      </div>
      <div class="col-auto">
        <span class="icon icon-add"></span>
      </div>
    </div>
  </button>
</div>